var autoprefixer = require('autoprefixer');
var env = process.env.NODE_ENV;
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var path = require('path');
var webpack = require('webpack');

const publicPath = 'static';

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: {
    js: './app/index.js',
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: `${publicPath}/bundle.js`,
  },
  resolve: {
    extensions: ['', '.js'],
    modules: [
      path.resolve('./app'),
      'node_modules',
    ],
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        include: path.join(__dirname, 'app'),
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader'),
      },
    ],
  },
  postcss: [autoprefixer({ browsers: ['last 3 versions'] })],
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(true),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(env),
    }),
    new ExtractTextPlugin(`${publicPath}/main.css`),
  ],
};

if (env === 'production') {
  delete module.exports.devtool;
  module.exports.plugins.push(
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: false,
      compress: {
        dead_code: true,
        pure_getters: true,
        unsafe: true,
        unsafe_comps: true,
        screw_ie8: true,
        warnings: false,
      },
    })
  );

  module.exports.plugins.push(
    new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false,
    })
  );

  module.exports.plugins.push(
    new HtmlWebpackPlugin({
      template: './app/index.html', // Move the index.html file...
      minify: { // Minifying it while it is parsed
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
      inject: true, // inject all files that are generated by webpack, e.g. bundle.js, main.css with the correct HTML tags
    })
  );

  // If app is in development
} else {
  module.exports.plugins.push(
    new HtmlWebpackPlugin({
      template: './app/index.html',
      inject: true,
    })
  );
}
